const mongoose = require('mongoose');

const payrollSchema = new mongoose.Schema(
  {
    employee: { type: mongoose.Schema.Types.ObjectId, ref: 'Employee', required: true },
    month: { type: mongoose.Schema.Types.Mixed, required: true }, // e.g. 7 or "2026-07"
    year: { type: Number },
    status: { type: String, default: 'draft' },
    basicSalary: { type: Number, required: true, default: 0 },
    regularOtHours: { type: Number, default: 0 },
    regularOtPay: { type: Number, default: 0 },
    doubleOtHours: { type: Number, default: 0 },
    doubleOtPay: { type: Number, default: 0 },
    allowances: { type: Number, default: 0 },
    overtime: { type: Number, default: 0 },
    overtimeHours: { type: Number, default: 0 },
    otHours: { type: Number, default: 0 },
    otPay: { type: Number, default: 0 },
    commissions: { type: Number, default: 0 },
    projectCommissions: { type: Number, default: 0 },
    bonus: { type: Number, default: 0 },
    bonusNote: { type: String, default: '' },
    incentives: { type: Number, default: 0 },
    advanceDeduction: { type: Number, default: 0 },
    loanDeduction: { type: Number, default: 0 },
    deductedLoans: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Loan' }],
    deductedAdvances: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Advance' }],
    leaveDeduction: { type: Number, default: 0 },
    penaltyDeduction: { type: Number, default: 0 },
    incomeTaxDeduction: { type: Number, default: 0 },
    epfEligibleAmount: { type: Number, default: 0 },
    epfEmployee: { type: Number, default: 0 },
    epfEmployer: { type: Number, default: 0 },
    etfEmployer: { type: Number, default: 0 },
    epfEmployee8Percent: { type: Number, default: 0 },
    epfEmployer12Percent: { type: Number, default: 0 },
    etfEmployer3Percent: { type: Number, default: 0 },
    apitTaxDeduction: { type: Number, default: 0 },
    deductions: { type: Number, default: 0 },
    otherDeductions: { type: mongoose.Schema.Types.Mixed, default: 0 },
    grossSalary: { type: Number, required: true, default: 0 },
    netSalary: { type: Number, default: 0 },
    netPay: { type: Number, default: 0 },
    paymentStatus: { type: String, enum: ['Pending', 'Approved', 'Paid', 'draft', 'reviewed', 'approved', 'paid'], default: 'Pending' },
    paidDate: { type: Date },
    autoSyncEnabled: { type: Boolean, default: true },
    recalcVersion: { type: Number, default: 1 },
    lastRecalculatedAt: { type: Date },
    lastRecalcSource: { type: String },
    notes: { type: String, default: '' },
    paymentMethod: { type: String },
    bankAccount: { type: mongoose.Schema.Types.ObjectId, ref: 'BankAccount' },
    reviewedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
    reviewedAt: { type: Date },
    generatedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  },
  { timestamps: true, strict: false }
);

module.exports = mongoose.model('Payroll', payrollSchema);
